from datetime import datetime
import configparser
import os
import shutil

class Module:

    # Synopsis: Return current timestamp in format YYYYmmDDHHMMSS
    # Usage: Useful for uniquefying autogenerated testdata
    def getnow_yyyymmddhhmmss():
        now = datetime.today()
        now_formatted = now.strftime('%Y%m%d%H%M%S')
        return now_formatted 
    
    # Synopsis: Updates appropriate runtimesettings_?.ini file based on given env name ?
    # with either creating a new key entry or updating an existing key entry for a given an existing section.
    # Usage: Useful for holding runtime test data item for reuse in other test scenarios
    def setrunsettings(envname, section,key,value):
        config = configparser.ConfigParser(allow_no_value=True)
        ini_path = os.path.join(os.getcwd(),'runsettings' + '_' + envname + '.ini')
        config.read(ini_path)
        config.set(section, key, value) 
        with open(ini_path, 'w') as configfile:
            config.write(configfile) 

    # Synopsis: Cleardown videos folder
    # Usage: For general housekeeping per run
    def cleardown_videos():
        folder = os.getcwd() + "\\videos"
        print(folder)
        shutil.rmtree(folder)
